### ISSUE TITLE
Plans of development?

### ISSUE THREAD

**Issue by AntonDzutstsati** [odrevet/yt-dlp-kivy#10]
What are plans for development of this app? Will it be some kind of an alternative to Seal / YTDLnis?

**Comment by odrevet** [comment]
I plan to build releases of this app on each release of ytdlp so the download plugins are up to dates. 
I did not know about Seal / YTDLnis apps, they sure do look nice and more polished than my app, so you are right, ytdlp-kivy is some alternatives to that. I started this project to test how yt_dlp may be integrated with kivy so it can be used under android without ffi and with a minimal code base, not that it matter for the end user

**Comment by error-reporting** [comment]
> I plan to build releases of this app on each release of ytdlp so the download plugins are up to dates. I did not know about Seal / YTDLnis apps, they sure do look nice and more polished than my app, so you are right, ytdlp-kivy is some alternatives to that. I started this project to test how yt_dlp may be integrated with kivy so it can be used under android without ffi and with a minimal code base, not that it matter for the end user

Yt-dlp has 2025.02.19 version

**Comment by odrevet** [comment]
I just released a new version with the latest version of yt-dlp
Did not had a lot of time lately to build new releases. Maybe using the CI to check new yt-dlp releases is the way.
