### ISSUE TITLE
Default download directory on Android isn't writeable

### ISSUE THREAD

**Issue by rspeed** [odrevet/yt-dlp-kivy#11]
After installing version 0.1.0 an attempt to download a video immediately failed with the error "cannot retrieve metadata, check logs". The default path for saving videos was set to "/sdcard", which apparently isn't writeable on my phone (Pixel 3, Android 11). Setting it to the Downloads directory fixed the issue.

**Comment by rspeed** [comment]
Though I'm still receiving similar warnings (rather than errors) due to another directory not being writeable: ![Screenshot_20230506-131149.png](https://user-images.githubusercontent.com/520459/236637845-60fb7bcf-1619-4852-a87d-744391262f36.png)

**Comment by odrevet** [comment]
Thanks for this reports, I will change the default save location to download. 
I also will try to fix the warnings if I can, according to the backtrace this is from  
https://github.com/yt-dlp/yt-dlp/blob/c449c0655d7c8549e6e1389c26b628053b253d39/yt_dlp/cache.py#L41
which itself call https://github.com/yt-dlp/yt-dlp/blob/c449c0655d7c8549e6e1389c26b628053b253d39/yt_dlp/cache.py#L20 
I will test to set XDG_CACHE_HOME

**Comment by odrevet** [comment]
I just changed the value of XDG_CACHE_HOME and the warning to not show up
